# Generated by Django 4.2.16 on 2025-09-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='ID заказа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay')], max_length=50, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
            },
        ),
    ]
