version: '3.8'

version: '3.8'

services:
  user-db:
    image: postgres:14
    environment:
      POSTGRES_DB: ecommerce_users
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_db_/var/lib/postgresql/data

  user-service:
    build: ./user-service
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./user-service:/app
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=user-db
      - DB_NAME=ecommerce_users
      - DB_USER=postgres1
      - DB_PASSWORD=postgres
      - SECRET_KEY=your-super-secret-key-change-in-prod
      - DEBUG=1
    depends_on:
      - user-db
    env_file:
      - ./user-service/.env

volumes:
  user_db_