# Generated by Django 4.2.16 on 2025-09-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('event_type', models.CharField(help_text='Например: order_created, payment_success', max_length=50, verbose_name='Тип события')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
